package com.nanoit.hub.couchbase.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(CouchbaseCustomProperties::class)
class CouchbaseCustomPropertiesConfiguration
