package com.nanoit.hub.scylla.entity

enum class Role {
    ADMINISTRATOR,
    STAFF,
    USERS_READ,
    USERS_WRITE,
    USERS_READ_WRITE,
    DEVICES_READ,
    DEVICES_WRITE,
    DEVICES_READ_WRITE,
    PROFILES_READ,
    PROFILES_WRITE,
    PROFILES_READ_WRITE,
    CONTACTS_READ,
    CONTACTS_WRITE,
    CONTACTS_READ_WRITE,
    MESSAGES_READ,
    MESSAGES_WRITE,
    MESSAGES_READ_WRITE,
    CALL_LOG_READ,
    CALL_LOG_WRITE,
    CALL_LOG_READ_WRITE,
}
